export interface Language {
  title: string
  code: string
  checked: boolean
}

export const languages: Language[] = [
  { title: 'All', code: 'all', checked: false },
  { title: 'Acehnese (Arabic script)', code: 'ace_Arab', checked: false },
  { title: 'Acehnese (Latin script)', code: 'ace_Latn', checked: false },
  { title: 'Afrikaans', code: 'afr_Latn', checked: false },
  { title: 'Akan', code: 'aka_Latn', checked: false },
  { title: 'Amharic', code: 'amh_Ethi', checked: false },
  { title: 'Armenian', code: 'hye_Armn', checked: false },
  { title: 'Assamese', code: 'asm_Beng', checked: false },
  { title: 'Asturian', code: 'ast_Latn', checked: false },
  { title: 'Awadhi', code: 'awa_Deva', checked: false },
  { title: 'Ayacucho Quechua', code: 'quy_Latn', checked: false },
  { title: 'Balinese', code: 'ban_Latn', checked: false },
  { title: 'Bambara', code: 'bam_Latn', checked: false },
  { title: 'Banjar (Arabic script)', code: 'bjn_Arab', checked: false },
  { title: 'Banjar (Latin script)', code: 'bjn_Latn', checked: false },
  { title: 'Bashkir', code: 'bak_Cyrl', checked: false },
  { title: 'Basque', code: 'eus_Latn', checked: false },
  { title: 'Belarusian', code: 'bel_Cyrl', checked: false },
  { title: 'Bemba', code: 'bem_Latn', checked: false },
  { title: 'Bengali', code: 'ben_Beng', checked: false },
  { title: 'Bhojpuri', code: 'bho_Deva', checked: false },
  { title: 'Bosnian', code: 'bos_Latn', checked: false },
  { title: 'Buginese', code: 'bug_Latn', checked: false },
  { title: 'Bulgarian', code: 'bul_Cyrl', checked: false },
  { title: 'Burmese', code: 'mya_Mymr', checked: false },
  { title: 'Catalan', code: 'cat_Latn', checked: false },
  { title: 'Cebuano', code: 'ceb_Latn', checked: false },
  { title: 'Central Atlas Tamazight', code: 'tzm_Tfng', checked: false },
  { title: 'Central Aymara', code: 'ayr_Latn', checked: false },
  { title: 'Central Kanuri (Arabic script)', code: 'knc_Arab', checked: false },
  { title: 'Central Kanuri (Latin script)', code: 'knc_Latn', checked: false },
  { title: 'Central Kurdish', code: 'ckb_Arab', checked: false },
  { title: 'Chhattisgarhi', code: 'hne_Deva', checked: false },
  { title: 'Chinese (Simplified)', code: 'zho_Hans', checked: false },
  { title: 'Chinese (Traditional)', code: 'zho_Hant', checked: false },
  { title: 'Chokwe', code: 'cjk_Latn', checked: false },
  { title: 'Crimean Tatar', code: 'crh_Latn', checked: false },
  { title: 'Croatian', code: 'hrv_Latn', checked: false },
  { title: 'Czech', code: 'ces_Latn', checked: false },
  { title: 'Danish', code: 'dan_Latn', checked: false },
  { title: 'Dari', code: 'prs_Arab', checked: false },
  { title: 'Dutch', code: 'nld_Latn', checked: false },
  { title: 'Dyula', code: 'dyu_Latn', checked: false },
  { title: 'Dzongkha', code: 'dzo_Tibt', checked: false },
  { title: 'Eastern Panjabi', code: 'pan_Guru', checked: false },
  { title: 'Eastern Yiddish', code: 'ydd_Hebr', checked: false },
  { title: 'Egyptian Arabic', code: 'arz_Arab', checked: false },
  { title: 'English', code: 'eng_Latn', checked: false },
  { title: 'Esperanto', code: 'epo_Latn', checked: false },
  { title: 'Estonian', code: 'est_Latn', checked: false },
  { title: 'Ewe', code: 'ewe_Latn', checked: false },
  { title: 'Faroese', code: 'fao_Latn', checked: false },
  { title: 'Fijian', code: 'fij_Latn', checked: false },
  { title: 'Finnish', code: 'fin_Latn', checked: false },
  { title: 'Fon', code: 'fon_Latn', checked: false },
  { title: 'French', code: 'fra_Latn', checked: false },
  { title: 'Friulian', code: 'fur_Latn', checked: false },
  { title: 'Galician', code: 'glg_Latn', checked: false },
  { title: 'Ganda', code: 'lug_Latn', checked: false },
  { title: 'Georgian', code: 'kat_Geor', checked: false },
  { title: 'German', code: 'deu_Latn', checked: false },
  { title: 'Greek', code: 'ell_Grek', checked: false },
  { title: 'Guarani', code: 'grn_Latn', checked: false },
  { title: 'Gujarati', code: 'guj_Gujr', checked: false },
  { title: 'Haitian Creole', code: 'hat_Latn', checked: false },
  { title: 'Halh Mongolian', code: 'khk_Cyrl', checked: false },
  { title: 'Hausa', code: 'hau_Latn', checked: false },
  { title: 'Hebrew', code: 'heb_Hebr', checked: false },
  { title: 'Hindi', code: 'hin_Deva', checked: false },
  { title: 'Hungarian', code: 'hun_Latn', checked: false },
  { title: 'Icelandic', code: 'isl_Latn', checked: false },
  { title: 'Igbo', code: 'ibo_Latn', checked: false },
  { title: 'Ilocano', code: 'ilo_Latn', checked: false },
  { title: 'Indonesian', code: 'ind_Latn', checked: false },
  { title: 'Irish', code: 'gle_Latn', checked: false },
  { title: 'Italian', code: 'ita_Latn', checked: false },
  { title: 'Japanese', code: 'jpn_Jpan', checked: false },
  { title: 'Javanese', code: 'jav_Latn', checked: false },
  { title: 'Jingpho', code: 'kac_Latn', checked: false },
  { title: 'Kabiyè', code: 'kbp_Latn', checked: false },
  { title: 'Kabuverdianu', code: 'kea_Latn', checked: false },
  { title: 'Kabyle', code: 'kab_Latn', checked: false },
  { title: 'Kamba', code: 'kam_Latn', checked: false },
  { title: 'Kannada', code: 'kan_Knda', checked: false },
  { title: 'Kashmiri (Arabic script)', code: 'kas_Arab', checked: false },
  { title: 'Kashmiri (Devanagari script)', code: 'kas_Deva', checked: false },
  { title: 'Kazakh', code: 'kaz_Cyrl', checked: false },
  { title: 'Khmer', code: 'khm_Khmr', checked: false },
  { title: 'Kikongo', code: 'kon_Latn', checked: false },
  { title: 'Kikuyu', code: 'kik_Latn', checked: false },
  { title: 'Kimbundu', code: 'kmb_Latn', checked: false },
  { title: 'Kinyarwanda', code: 'kin_Latn', checked: false },
  { title: 'Korean', code: 'kor_Hang', checked: false },
  { title: 'Kyrgyz', code: 'kir_Cyrl', checked: false },
  { title: 'Lao', code: 'lao_Laoo', checked: false },
  { title: 'Latgalian', code: 'ltg_Latn', checked: false },
  { title: 'Ligurian', code: 'lij_Latn', checked: false },
  { title: 'Limburgish', code: 'lim_Latn', checked: false },
  { title: 'Lingala', code: 'lin_Latn', checked: false },
  { title: 'Lithuanian', code: 'lit_Latn', checked: false },
  { title: 'Lombard', code: 'lmo_Latn', checked: false },
  { title: 'Luba-Kasai', code: 'lua_Latn', checked: false },
  { title: 'Luo', code: 'luo_Latn', checked: false },
  { title: 'Luxembourgish', code: 'ltz_Latn', checked: false },
  { title: 'Macedonian', code: 'mkd_Cyrl', checked: false },
  { title: 'Magahi', code: 'mag_Deva', checked: false },
  { title: 'Maithili', code: 'mai_Deva', checked: false },
  { title: 'Malayalam', code: 'mal_Mlym', checked: false },
  { title: 'Maltese', code: 'mlt_Latn', checked: false },
  { title: 'Maori', code: 'mri_Latn', checked: false },
  { title: 'Marathi', code: 'mar_Deva', checked: false },
  { title: 'Meitei (Bengali script)', code: 'mni_Beng', checked: false },
  { title: 'Mesopotamian Arabic', code: 'acm_Arab', checked: false },
  { title: 'Minangkabau (Arabic script)', code: 'min_Arab', checked: false },
  { title: 'Minangkabau (Latin script)', code: 'min_Latn', checked: false },
  { title: 'Mizo', code: 'lus_Latn', checked: false },
  // {
  //   title: 'Modern Standard Arabic (Romanized)',
  //   code: 'arb_Latn',
  //   checked: false,
  // },
  { title: 'Modern Standard Arabic', code: 'arb_Arab', checked: false },
  { title: 'Moroccan Arabic', code: 'ary_Arab', checked: false },
  { title: 'Mossi', code: 'mos_Latn', checked: false },
  { title: 'Najdi Arabic', code: 'ars_Arab', checked: false },
  { title: 'Nepali', code: 'npi_Deva', checked: false },
  { title: 'Nigerian Fulfulde', code: 'fuv_Latn', checked: false },
  { title: 'North Azerbaijani', code: 'azj_Latn', checked: false },
  { title: 'North Levantine Arabic', code: 'apc_Arab', checked: false },
  { title: 'Northern Kurdish', code: 'kmr_Latn', checked: false },
  { title: 'Northern Sotho', code: 'nso_Latn', checked: false },
  { title: 'Northern Uzbek', code: 'uzn_Latn', checked: false },
  { title: 'Norwegian Bokmål', code: 'nob_Latn', checked: false },
  { title: 'Norwegian Nynorsk', code: 'nno_Latn', checked: false },
  { title: 'Nuer', code: 'nus_Latn', checked: false },
  { title: 'Nyanja', code: 'nya_Latn', checked: false },
  { title: 'Occitan', code: 'oci_Latn', checked: false },
  { title: 'Odia', code: 'ory_Orya', checked: false },
  { title: 'Pangasinan', code: 'pag_Latn', checked: false },
  { title: 'Papiamento', code: 'pap_Latn', checked: false },
  { title: 'Plateau Malagasy', code: 'plt_Latn', checked: false },
  { title: 'Polish', code: 'pol_Latn', checked: false },
  { title: 'Portuguese', code: 'por_Latn', checked: false },
  { title: 'Romanian', code: 'ron_Latn', checked: false },
  { title: 'Rundi', code: 'run_Latn', checked: false },
  { title: 'Russian', code: 'rus_Cyrl', checked: false },
  { title: 'Samoan', code: 'smo_Latn', checked: false },
  { title: 'Sango', code: 'sag_Latn', checked: false },
  { title: 'Sanskrit', code: 'san_Deva', checked: false },
  // { title: 'Santali', code: 'sat_Olck', checked: false },
  { title: 'Sardinian', code: 'srd_Latn', checked: false },
  { title: 'Scottish Gaelic', code: 'gla_Latn', checked: false },
  { title: 'Serbian', code: 'srp_Cyrl', checked: false },
  { title: 'Shan', code: 'shn_Mymr', checked: false },
  { title: 'Shona', code: 'sna_Latn', checked: false },
  { title: 'Sicilian', code: 'scn_Latn', checked: false },
  { title: 'Silesian', code: 'szl_Latn', checked: false },
  { title: 'Sindhi', code: 'snd_Arab', checked: false },
  { title: 'Sinhala', code: 'sin_Sinh', checked: false },
  { title: 'Slovak', code: 'slk_Latn', checked: false },
  { title: 'Slovenian', code: 'slv_Latn', checked: false },
  { title: 'Somali', code: 'som_Latn', checked: false },
  { title: 'South Azerbaijani', code: 'azb_Arab', checked: false },
  { title: 'South Levantine Arabic', code: 'ajp_Arab', checked: false },
  { title: 'Southern Pashto', code: 'pbt_Arab', checked: false },
  { title: 'Southern Sotho', code: 'sot_Latn', checked: false },
  { title: 'Southwestern Dinka', code: 'dik_Latn', checked: false },
  { title: 'Spanish', code: 'spa_Latn', checked: false },
  { title: 'Standard Latvian', code: 'lvs_Latn', checked: false },
  { title: 'Standard Malay', code: 'zsm_Latn', checked: false },
  { title: 'Standard Tibetan', code: 'bod_Tibt', checked: false },
  { title: 'Sundanese', code: 'sun_Latn', checked: false },
  { title: 'Swahili', code: 'swh_Latn', checked: false },
  { title: 'Swati', code: 'ssw_Latn', checked: false },
  { title: 'Swedish', code: 'swe_Latn', checked: false },
  { title: 'Tagalog', code: 'tgl_Latn', checked: false },
  { title: 'Tajik', code: 'tgk_Cyrl', checked: false },
  { title: 'Tamasheq (Latin script)', code: 'taq_Latn', checked: false },
  { title: 'Tamasheq (Tifinagh script)', code: 'taq_Tfng', checked: false },
  { title: 'Tamil', code: 'tam_Taml', checked: false },
  { title: 'Tatar', code: 'tat_Cyrl', checked: false },
  { title: 'Ta’izzi-Adeni Arabic', code: 'acq_Arab', checked: false },
  { title: 'Telugu', code: 'tel_Telu', checked: false },
  { title: 'Thai', code: 'tha_Thai', checked: false },
  { title: 'Tigrinya', code: 'tir_Ethi', checked: false },
  { title: 'Tok Pisin', code: 'tpi_Latn', checked: false },
  { title: 'Tosk Albanian', code: 'als_Latn', checked: false },
  { title: 'Tsonga', code: 'tso_Latn', checked: false },
  { title: 'Tswana', code: 'tsn_Latn', checked: false },
  { title: 'Tumbuka', code: 'tum_Latn', checked: false },
  { title: 'Tunisian Arabic', code: 'aeb_Arab', checked: false },
  { title: 'Turkish', code: 'tur_Latn', checked: false },
  { title: 'Turkmen', code: 'tuk_Latn', checked: false },
  { title: 'Twi', code: 'twi_Latn', checked: false },
  { title: 'Ukrainian', code: 'ukr_Cyrl', checked: false },
  { title: 'Umbundu', code: 'umb_Latn', checked: false },
  { title: 'Urdu', code: 'urd_Arab', checked: false },
  { title: 'Uyghur', code: 'uig_Arab', checked: false },
  { title: 'Venetian', code: 'vec_Latn', checked: false },
  { title: 'Vietnamese', code: 'vie_Latn', checked: false },
  { title: 'Waray', code: 'war_Latn', checked: false },
  { title: 'Welsh', code: 'cym_Latn', checked: false },
  { title: 'West Central Oromo', code: 'gaz_Latn', checked: false },
  { title: 'Western Persian', code: 'pes_Arab', checked: false },
  { title: 'Wolof', code: 'wol_Latn', checked: false },
  { title: 'Xhosa', code: 'xho_Latn', checked: false },
  { title: 'Yoruba', code: 'yor_Latn', checked: false },
  { title: 'Yue Chinese', code: 'yue_Hant', checked: false },
  { title: 'Zulu', code: 'zul_Latn', checked: false },
]

export const PRICE_LOOKUP_KEY = 'i18n-base-product'
